fail_fast: true

repos:
  - repo: local
    hooks:
      - id: images.sh
        name: "Create: images.sh"
        description: Create images.sh
        language: system
        entry: echo
#        entry: tools/images.sh images-sh
        stages:
          - commit
        pass_filenames: false

      - id: hooks
        name: "Update: hooks"
        description: Update hooks
        language: system
        entry: echo
#        entry: tools/images.sh hooks
        stages:
          - commit
        pass_filenames: false

      - id: testing
        name: "post-commit: testing build images"
        description: post commit testing build images
        language: system
        entry: echo
#        entry: tests/build.sh build
        stages:
          - post-commit
        pass_filenames: false

      - id: testing
        name: "post-commit: testing remove images"
        description: post commit testing remove images
        language: system
        entry: echo
#        entry: tests/build.sh remove
        stages:
          - post-commit
        pass_filenames: false

      - id: testing
        name: "post-commit: prune"
        description: post commit prune
        language: system
        entry: echo
#        entry: docker images prune
        stages:
          - post-commit
        pass_filenames: false

      # TODO: pre-push hook con tag y opciones (no vale por la version)
      - id: pre-push
        name: "tag"
        description: pre-push tag
        language: system
        entry: echo
#        entry: echo pre-push
        stages:
          - push
        pass_filenames: false
