#!/usr/bin/env bash
# shellcheck disable=SC2207,SC2086,SC1090
#
# System bootstrap install
# Copyright 2021 j5pux

_btrap()
{
    local cur prev before

    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    before=${COMP_WORDS[COMP_CWORD-2]}
    if [ "${DEBUG-}" ]; then
      echo -e "\nCOMP_WORDS[@]: $( printf '%s,' "${COMP_WORDS[@]}" )"  >&2
      echo "len COMP_WORDS[@]: ${#COMP_WORDS[@]}"  >&2
      echo "COMP_LINE[@]: $( printf '%s,' "${COMP_LINE[@]}" )"  >&2
      echo "len COMP_LINE[@]: ${#COMP_LINE[@]}"  >&2
      echo "cur: ${cur}"  >&2
      echo "prev: ${prev}"  >&2
      echo "before: ${before}"  >&2
    fi

    case "${cur}" in
      -h|--help|--internet|--password) return ;;
      *)
        case "${before}" in
          --internet)
            if [ "${COMP_WORDS[COMP_CWORD-4]}" == "--password" ]; then
              return
            fi
            COMPREPLY=($(compgen -W "--password" -- ${cur})); return ;;
          --password)
            if [ "${COMP_WORDS[COMP_CWORD-4]}" == "--internet" ]; then
              return
            fi
            COMPREPLY=($(compgen -W "--internet" -- ${cur})); return ;;
        esac
        COMPREPLY=($(compgen -W "--internet --password -h --help" -- ${cur}))
        ;;
    esac
}

#######################################
# Debug and stderr files
logs() {
  local debug stderr
  debug="${name}.debug"
  stderr="${name}.stderr"
  rm -f "${debug}"
  rm -f "${stderr}"
  exec 19>"${debug}"
  export BASH_XTRACEFD=19
  set -x
  exec > >(tee "${stderr}") 2>&1
}

#######################################
# System bootstrap install
# Globals:
#   INTERNET            internet password
#   PASSWORD            user/sudo password
# Options:
#   --internet value    internet password (default: \$INTERNET)
#   --password value    user/sudo password (default: \$PASSWORD)
# Global Arguments:
#   -h, --help        show help and exit
main() {
  local args=() internet password scripts=()
  declare -g name="${BASH_SOURCE[0]##*/}"

  cd /tmp || return 1

  if ((${BASH_LINENO[1]:-0} != 0)); then
    # I am sourced.
    complete -r "${name}"
    complete -F "_${name}" "${name}"
    return
  fi


  logs

  while ((${#})); do
    case "${1}" in
      -h|--help)
        args+=("${1}")
        cat<<EOF
Usage: ${0##*/} [options...] [arguments...]

Description:
  Boostrap all if not options are passed.

Arguments:
  -h,  --help         show help and exit

Options:
  --internet value    internet password (default: \$INTERNET)
  --password value    user/sudo password (default: \$PASSWORD)
  --clt               install Command Line Tools (default: True)
EOF
        return
      ;;
    --internet)
      args+=("${1}")
      if [[ ! "${2}" =~ ^-- ]]; then
        shift; internet="${1}"
      fi
      ;;
    --password)
      args+=("${1}")
      if [[ ! "${2}" =~ ^-- ]]; then
        shift; password="${1}"
      fi
      ;;
    *)
      args+=("${1}")
      scripts+=("${compat}/${1/--/}.sh")
    esac
    shift
  done

  echo "${internet:-${INTERNET}}, ${password:-${PASSWORD}}"
  printf '%s\n' "${args[@]}"
  printf '%s\n' "${scripts[@]}"
}

main "${@}"
