#!/bin/sh
https://gist.github.com/j5pux/f3b483feb94becc84869afb4e3370afd
<script src="https://gist.github.com/j5pux/f3b483feb94becc84869afb4e3370afd.js"></script>
https://gist.github.com/j5pux/f3b483feb94becc84869afb4e3370afd/archive/5edc42dcc4ce470b9ae7a853a3210799c626df78.zip

https://snippets.cacher.io/snippet/b6667b4b9cf585e8b4b4
https://snippets.cacher.io/snippet/b6667b4b9cf585e8b4b4
https://snippets.cacher.io/snippet/532ee6693d7d3bd9c038
https://json.extendsclass.com/bin/46c90761bb91
https://extendsclass.com/jsonstorage/46c90761bb91
https://pastebin.com/heu2cDzB
https://pastebin.com/raw/heu2cDzB
