  version: '3'

  tasks:
    clean:
      - rm -rf tests/output

    tests-lib:
      - git submodule init && git submodule update

    tests:
      deps: [clean]
      cmds:
        - "bats tests --gather-test-outputs-in tests/output --no-tempdir-cleanup --output tests/output \
                      --print-output-on-failure --recursive --timing --trace --verbose-run"
